name: test-bench

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses:
      - name: Setup Python
        uses:
          python-version: '3.x'
      - name: Install Poetry
        run: |
          curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
          python get-poetry.py -y
          echo "::set-env name=PATH::$HOME/.poetry/bin:$PATH"
      - name: Configure Poetry
        uses: poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: pip install .[dev]
      - name: Test with PyTest and Code Coverage
        run: poetry run pytest --cov